version: "3.8"

services:
  chatbot:
    image: mehdixlabetix/chatbot-backend:latest
    ports:
      - "5000:5000"
    volumes:
      - ./static/embeddings:/app/static/embeddings

    links:
      - mongo
      - ollama
    depends_on:
      - mongo
      - ollama
    environment:
      - HOST = ${HOST}
      - PORT = ${PORT}
      - DB_NAME = ${DB_NAME}
      - COLLECTION_NAME = ${COLLECTION_NAME}
      - GOOGLE_API_KEY = ${GOOGLE_API_KEY}
      - PINECONE_API_KEY = ${PINECONE_API_KEY}
      - INDEX_NAME = ${INDEX_NAME}
      - LANGCHAIN_TRACING_V2 = ${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_ENDPOINT = ${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_API_KEY = ${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT = ${LANGCHAIN_PROJECT}
      - GROQ_API_KEY = ${GROQ_API_KEY} 
      - CLERK_PUBLIC_KEY = ${CLERK_PUBLIC_KEY}
    restart: always
    networks:
      - app-network
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=PFA
    ports:
      - "27017:27017"   
    restart: always 
    networks:
      - app-network
  ollama:
    image: mehdixlabetix/mistral-ollama:latest
    ports:
      - "11434:11434"  
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - app-network
networks:
  app-network: 
    driver: bridge    