version: "3.8"

services:
  chatbot:
    image: mehdixlabetix/chatbot-backend:latest
    ports:
      - "5000:5000"
    links:
      - mongo
      - ollama
    depends_on:
      - mongo
      - ollama
    restart: always
    networks:
      - app-network
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=PFA
    ports:
      - "27017:27017"   
    restart: always 
    networks:
      - app-network
  ollama:
    image: mehdixlabetix/mistral-ollama:latest
    ports:
      - "11434:11434"  
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - app-network
networks:
  app-network: 
    driver: bridge    