name: Build and Push Docker Image (Chatbot Backend)

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest  # Or another runner with Docker installed

    steps:
      - uses: actions/checkout@v3  # Latest recommended version

      - name: Check for Docker Hub credentials
        id: check_secrets
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ] || [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "credentials_present=false" >> $GITHUB_ENV
          else
            echo "credentials_present=true" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub (if pushing)
        if: env.credentials_present == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chatbot-backend:latest .

      - name: Push the Docker image (if pushing)
        if: env.credentials_present == 'true'
        uses: docker/push-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: mehdixlabetix/chatbot-backend
