name: Build and Push Docker Image (Chatbot Backend)

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest  # Or another runner with Docker installed

    steps:
      - uses: actions/checkout@v3  # Latest recommended version

      - name: Set up Docker Hub credentials
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}  # Check for login credentials
        run: echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV
             echo "DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Login to Docker Hub (if pushing)
        if: ${{ env.DOCKERHUB_USERNAME }}  # Optional: Check for login credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chatbot-backend:latest .  # Use dynamic version tag or your preferred naming convention

      - name: Push the Docker image (if pushing)
        if: ${{ env.DOCKERHUB_USERNAME }}  # Optional: Only push if credentials are available
        uses: docker/push-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/chatbot-backend:latest
