name: Build and Push Docker Image (Chatbot Backend)

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest  # Or another runner with Docker installed

    steps:
      - uses: actions/checkout@v3  # Latest recommended version

      - name: Check for Docker Hub credentials
        id: check_secrets
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ] || [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "credentials_present=false" >> $GITHUB_ENV
          else
            echo "credentials_present=true" >> $GITHUB_ENV

      - name: Build & push Docker image
        if: env.credentials_present == 'true'
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/chatbot-backend
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
