name: Build and Push Docker Image (Chatbot Backend)

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest  # Or another runner with Docker installed

    steps:       
      - name: Push to Docker
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: mehdixlabetix/chatbot-backend
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
